<?php

namespace ContainerJ4qMLuY;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CKNmilYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CKNmilY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CKNmilY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'tweetRepository' => ['privates', 'App\\Repository\\TweetRepository', 'getTweetRepositoryService', true],
        ], [
            'entityManager' => '?',
            'tweetRepository' => 'App\\Repository\\TweetRepository',
        ]);
    }
}
